/**
 * jobs-sources.v1 — the policy-only lane the jobs routine reaches job boards,
 * aggregators, union / apprenticeship channels and employer ATS career
 * pages through.
 *
 * 2026-09-13: the operator directed, in the live CI session, that the jobs
 * dashboard's default sources and the connectors it uses be expanded, and
 * ratified the roster in-session on the office-sources.v1 precedent (the
 * backlog row had waited since 2026-09-04 on an ORIGIN_DENIED no fire had
 * spent). The profile is generated by createResearchProfile, so what this
 * file pins is the roster itself, the job-board walls (apply, resume, alert,
 * save, message), the backlog row's own requirement that a Job Bank posting
 * URL carrying ?applyonline=false is NOT an endpoint, and that the lane
 * composes with the five existing profiles without loosening any of them.
 */
import { describe, expect, it } from 'vitest';
import {
  checkUrl,
  hostMatchesAllowlist,
  isAuthPathBlocked,
  isProtectedEndpoint,
  mergeSiteProfiles,
} from '@browser-bridge/policy';
import { ebaySiteProfile } from '@browser-bridge/site-ebay';
import {
  isJobsSourceHost,
  JOBS_SOURCES,
  JOBS_SOURCES_SITE_PROFILE_ID,
  jobsSourceLabelForHost,
  jobsSourcesSiteProfile,
} from '@browser-bridge/site-jobs';
import { kijijiSiteProfile } from '@browser-bridge/site-kijiji';
import { officeSourcesSiteProfile } from '@browser-bridge/site-office';
import { wardrobeVendorsSiteProfile } from '@browser-bridge/site-vendors';
import { zazzleSiteProfile } from '@browser-bridge/site-zazzle';

const publicResolve = async () => ['23.55.0.10'];

describe('jobs-sources.v1 roster', () => {
  it('is a production profile with a versioned id and no test escapes', () => {
    expect(jobsSourcesSiteProfile.id).toBe('jobs-sources.v1');
    expect(JOBS_SOURCES_SITE_PROFILE_ID).toBe(jobsSourcesSiteProfile.id);
    expect(jobsSourcesSiteProfile.testOnly).toBeUndefined();
  });

  it('covers every host the 2026-09-13 ratification named, apex and subdomains', () => {
    const hosts = jobsSourcesSiteProfile.allowedHosts;
    for (const host of [
      // boards
      'www.jobbank.gc.ca', 'jobbank.gc.ca', 'ca.indeed.com', 'to.indeed.com', 'www.indeed.com', 'ca.talent.com',
      'www.eluta.ca', 'www.jobillico.com', 'www.simplyhired.ca', 'www.glassdoor.ca', 'www.workopolis.com',
      'www.linkedin.com', 'ca.linkedin.com', 'www.ziprecruiter.com',
      // aggregators
      'www.adzuna.ca', 'ca.jooble.org', 'www.careerbeacon.com',
      // channels
      'www.ualocal46.org', 'ualocal46.org', 'smwia-l30.com', 'iw721.org', 'liunalocal183.ca',
      'www.skilledtradesontario.ca', 'www.apprenticesearch.com', 'www.ontario.ca', 'www.georgebrown.ca',
      // ATS hosts
      'canam.wd3.myworkdayjobs.com', 'jobs.smartrecruiters.com', 'boards.greenhouse.io', 'jobs.lever.co',
      'mariani.bamboohr.com', 'careers-matcor.icims.com', 'jobs.jobvite.com', 'visionhollowmetal.applytojob.com',
      'clients.njoyn.com', 'recruiting.ultipro.com', 'workforcenow.adp.com',
    ]) {
      expect(hostMatchesAllowlist(host, hosts), host).toBe(true);
      expect(isJobsSourceHost(host), host).toBe(true);
    }
  });

  it('every roster entry names a public registrable domain (or a narrower host), a group, a source label and a source', () => {
    expect(JOBS_SOURCES.length).toBeGreaterThanOrEqual(31);
    const labels = new Set<string>();
    for (const source of JOBS_SOURCES) {
      expect(['board', 'aggregator', 'channel', 'ats']).toContain(source.group);
      expect(source.hosts.length).toBeGreaterThan(0);
      for (const host of source.hosts) {
        expect(host, host).toMatch(/^[a-z0-9-]+(?:\.[a-z0-9-]+)+$/);
        expect(host, host).not.toMatch(/^\d+\.\d+\.\d+\.\d+$/);
        expect(host, host).not.toMatch(/^\*/);
      }
      expect(source.addedOn).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(source.source).toContain('jobs-default-sources-and-connectors-expansion-2026-09-13');
      expect(source.sourceLabel.length).toBeGreaterThan(0);
      labels.add(source.sourceLabel);
      if (source.group === 'ats') expect(source.sourceLabel).toBe('employer-direct');
      if (source.group === 'channel') expect(source.sourceLabel).toBe('union');
    }
    // Every label is a value of the jobs record's closed `source` vocabulary
    // (fluxlab-boards public/jobs/data/schema.json after the 2026-09-13 widening).
    for (const label of labels) {
      expect([
        'Job Bank', 'Indeed', 'Kijiji', 'employer-direct', 'LinkedIn', 'Glassdoor', 'ZipRecruiter', 'Workopolis',
        'SimplyHired', 'talent.com', 'Eluta', 'Jobillico', 'Adzuna', 'Jooble', 'CareerBeacon', 'union', 'other',
      ]).toContain(label);
    }
  });

  it('maps a host to the discovery-source label the routine writes', () => {
    expect(jobsSourceLabelForHost('https://www.jobbank.gc.ca/jobsearch/jobposting/50193006')).toBe('Job Bank');
    expect(jobsSourceLabelForHost('https://ca.indeed.com/viewjob?jk=a18e85115521a680')).toBe('Indeed');
    expect(jobsSourceLabelForHost('to.indeed.com')).toBe('Indeed');
    expect(jobsSourceLabelForHost('https://jobs.smartrecruiters.com/Canam/743999')).toBe('employer-direct');
    expect(jobsSourceLabelForHost('https://www.ualocal46.org/training/application-process')).toBe('union');
    expect(jobsSourceLabelForHost('https://www.kijiji.ca/b-jobs/gta')).toBeNull();
  });

  it('the ADP and UKG entries are the recruiting hosts only: the payroll apexes stay out', () => {
    const hosts = jobsSourcesSiteProfile.allowedHosts;
    expect(hostMatchesAllowlist('workforcenow.adp.com', hosts)).toBe(true);
    expect(hostMatchesAllowlist('www.adp.com', hosts)).toBe(false);
    expect(hostMatchesAllowlist('adp.com', hosts)).toBe(false);
    expect(hostMatchesAllowlist('recruiting.ultipro.com', hosts)).toBe(true);
    expect(hostMatchesAllowlist('www.ultipro.com', hosts)).toBe(false);
    expect(isJobsSourceHost('https://online.adp.com/olp/olplanding.html')).toBe(false);
  });

  it('never matches lookalikes, marketplaces or the hosts other profiles own', () => {
    const hosts = jobsSourcesSiteProfile.allowedHosts;
    for (const host of [
      'notindeed.com', 'indeed.com.attacker.io', 'jobbank.gc.ca.evil.example', 'linkedin.com.example',
      'www.kijiji.ca', 'www.ebay.ca', 'www.zazzle.ca', 'www.regus.com', 'www.vistaprint.ca', 'craigslist.org',
      'www.monster.ca', 'jooble.com',
    ]) {
      expect(hostMatchesAllowlist(host, hosts), host).toBe(false);
      expect(isJobsSourceHost(host), host).toBe(false);
    }
    expect(isJobsSourceHost('not a host')).toBe(false);
    expect(jobsSourceLabelForHost('not a host')).toBeNull();
  });

  it('allows search pages, posting pages, channel pages and ATS career pages, and blocks apply, resume, alert, saved-job and sign-in paths', async () => {
    for (const url of [
      'https://www.jobbank.gc.ca/jobsearch/jobsearch?searchstring=welder+helper&locationstring=Toronto%2C+ON&sort=D&fprov=ON',
      'https://www.jobbank.gc.ca/jobsearch/jobposting/50193006?source=searchresults',
      'https://ca.indeed.com/viewjob?jk=a18e85115521a680',
      'https://ca.indeed.com/jobs?q=welder+helper&l=Toronto%2C+ON',
      'https://www.linkedin.com/jobs/view/4012345678/',
      'https://www.glassdoor.ca/Job/toronto-welder-helper-jobs-SRCH_IL.0,7_IC2281069_KO8,21.htm',
      'https://www.ualocal46.org/training/application-process',
      'https://iw721.org/training/apprenticeship/ironworkers/',
      'https://www.skilledtradesontario.ca/trade-information/welder/',
      'https://www.apprenticesearch.com/jobs/ontario/welding',
      'https://jobs.smartrecruiters.com/Canam/743999999-welder-tacking-day-shift',
      'https://canam.wd3.myworkdayjobs.com/en-US/careers/job/Mississauga/Welder_R1234',
      'https://boards.greenhouse.io/matcor/jobs/1234567',
      'https://jobs.lever.co/visionhollow/1a2b3c4d',
      'https://mariani.bamboohr.com/careers/42',
      'https://careers-matcor.icims.com/jobs/1234/welder-helper/job',
      'https://clients.njoyn.com/CL4/xweb/xweb.asp?clid=1234&page=jobdetails&jobid=J0925-0001',
      'https://recruiting.ultipro.com/ABC1000XYZ/JobBoard/aaaa-bbbb/OpportunityDetail?opportunityId=1',
    ]) {
      const decision = await checkUrl(url, jobsSourcesSiteProfile, 'navigation', { resolve: publicResolve });
      expect(decision.allowed, url).toBe(true);
      expect(isProtectedEndpoint(url, jobsSourcesSiteProfile), url).toBe(false);
    }
    for (const url of [
      'https://www.jobbank.gc.ca/jobsearch/jobposting/50193006/apply',
      'https://ca.indeed.com/apply/123',
      'https://ca.indeed.com/profile/resume',
      'https://ca.indeed.com/saved-jobs',
      'https://www.linkedin.com/jobs/view/4012345678/apply/',
      'https://www.linkedin.com/messaging/thread/2-abc/',
      'https://www.glassdoor.ca/member/profile/',
      // Glassdoor's sign-in page: the auth wall keys on whole segments, so
      // login_input.htm is not an auth path — the profile segment walls it.
      'https://www.glassdoor.ca/profile/login_input.htm',
      'https://www.ziprecruiter.com/candidate/apply/12345',
      'https://boards.greenhouse.io/matcor/jobs/1234567/application',
      'https://jobs.lever.co/visionhollow/1a2b3c4d/apply',
      'https://mariani.bamboohr.com/careers/42/application',
      'https://canam.wd3.myworkdayjobs.com/en-US/careers/job/Welder_R1234/apply',
      'https://www.eluta.ca/job-alerts',
      'https://www.ualocal46.org/application',
      'https://www.simplyhired.ca/resumes/upload',
    ]) {
      expect(isProtectedEndpoint(url, jobsSourcesSiteProfile), url).toBe(true);
    }
    for (const url of [
      'https://ca.indeed.com/account/login',
      'https://www.linkedin.com/login',
      'https://www.simplyhired.ca/account/login',
      'https://canam.wd3.myworkdayjobs.com/en-US/careers/login',
      'https://workforcenow.adp.com/mascsr/default/login',
    ]) {
      expect(isAuthPathBlocked(url, jobsSourcesSiteProfile), url).toBe(true);
      const decision = await checkUrl(url, jobsSourcesSiteProfile, 'navigation', { resolve: publicResolve });
      expect(decision.allowed, url).toBe(false);
    }
  });

  // The backlog row's own requirement: a Job Bank posting URL carrying
  // ?applyonline=false is a posting page, not an apply endpoint — the apply
  // wall is segment-anchored on the path and never reads the query string.
  it('a Job Bank posting URL carrying ?applyonline=false is NOT an endpoint', async () => {
    const url = 'https://www.jobbank.gc.ca/jobsearch/jobposting/50193006?applyonline=false&source=searchresults';
    expect(isProtectedEndpoint(url, jobsSourcesSiteProfile)).toBe(false);
    expect(isAuthPathBlocked(url, jobsSourcesSiteProfile)).toBe(false);
    const decision = await checkUrl(url, jobsSourcesSiteProfile, 'navigation', { resolve: publicResolve });
    expect(decision.allowed).toBe(true);
  });

  // A posting slug is employer-written text: an endpoint word inside it is not an endpoint.
  it('does not treat an endpoint word inside a posting slug or an ATS host name as an endpoint', () => {
    for (const url of [
      'https://ca.indeed.com/q-resume-writer-l-toronto,-on-jobs.html',
      'https://www.jobbank.gc.ca/jobsearch/jobsearch?searchstring=order+desk+helper&fprov=ON',
      'https://www.linkedin.com/jobs/view/candidate-experience-coordinator-at-example-4012345678/',
      'https://visionhollowmetal.applytojob.com/apply-to-job-shop-helper-listing/1234',
      'https://www.eluta.ca/jobs/welder-apply-ready-shop-helper',
      'https://jobs.smartrecruiters.com/Canam/743999-account-manager-piping-profiles',
    ]) {
      expect(isProtectedEndpoint(url, jobsSourcesSiteProfile), url).toBe(false);
      expect(isAuthPathBlocked(url, jobsSourcesSiteProfile), url).toBe(false);
    }
    // …but the host name applytojob.com is allowed while its /apply path is not.
    expect(isProtectedEndpoint('https://visionhollowmetal.applytojob.com/apply/1234', jobsSourcesSiteProfile)).toBe(true);
  });

  it('refuses the apply, save, alert, upload and contact controls by accessible name, on top of the generic set', () => {
    for (const name of [
      'apply', 'apply now', 'easy apply', 'quick apply', 'apply on company site', 'apply with indeed', 'start application',
      'save job', 'create job alert', 'email me jobs', 'upload resume', 'upload your cv', 'message recruiter',
      'contact employer', 'follow company', 'sign in', 'log in', 'create account', 'add to cart',
    ]) {
      expect(jobsSourcesSiteProfile.blockedActionPatterns, name).toContain(name);
    }
    expect(jobsSourcesSiteProfile.blockedFieldAutocomplete).toEqual(
      expect.arrayContaining(['current-password', 'new-password', 'one-time-code', 'cc-number', 'cc-exp', 'cc-csc']),
    );
  });

  it('is no weaker than the hand-written wardrobe lane or the generated office lane', () => {
    expect(jobsSourcesSiteProfile.blockedActionPatterns).toEqual(
      expect.arrayContaining([...wardrobeVendorsSiteProfile.blockedActionPatterns]),
    );
    expect(jobsSourcesSiteProfile.blockedFieldAutocomplete).toEqual(officeSourcesSiteProfile.blockedFieldAutocomplete);
  });

  it('composes with the five existing profiles without loosening any of them', () => {
    const composite = mergeSiteProfiles([
      ebaySiteProfile,
      kijijiSiteProfile,
      zazzleSiteProfile,
      wardrobeVendorsSiteProfile,
      officeSourcesSiteProfile,
      jobsSourcesSiteProfile,
    ]);
    expect(composite.id).toBe('ebay.ca.v1+kijiji.ca.v1+zazzle.com.v1+wardrobe-vendors.v1+office-sources.v1+jobs-sources.v1');
    expect(hostMatchesAllowlist('ca.indeed.com', composite.allowedHosts)).toBe(true);
    expect(hostMatchesAllowlist('www.regus.com', composite.allowedHosts)).toBe(true);
    expect(hostMatchesAllowlist('www.ebay.ca', composite.allowedHosts)).toBe(true);
    expect(isProtectedEndpoint('https://www.ebay.ca/placebid?item=1', composite)).toBe(true);
    expect(isProtectedEndpoint('https://www.zazzle.ca/co/cart', composite)).toBe(true);
    expect(isProtectedEndpoint('https://www.regus.com/en-ca/booking/confirm', composite)).toBe(true);
    expect(isProtectedEndpoint('https://ca.indeed.com/apply/123', composite)).toBe(true);
    expect(composite.deniedHosts).toEqual(expect.arrayContaining(['entripy.com']));
  });
});
