/**
 * office-sources.v1 — the policy-only lane the office routine reaches GTA
 * managed-office providers and commercial listing surfaces through.
 *
 * 2026-09-05: the office fire's 13:50Z report carried the live ORIGIN_DENIED
 * ("Host www.regus.com is not in the ebay.ca.v1+kijiji.ca.v1+zazzle.com.v1+
 * wardrobe-vendors.v1 allowlist") that docs/SITE-PROFILE-BACKLOG.md named as
 * the one thing the office-sources.v1 row still needed, and the operator
 * ratified the roster in-session. The profile is generated by
 * createResearchProfile, so what this file pins is the roster itself, the
 * office-specific accessible-name walls, and that the lane composes with the
 * marketplace profiles without loosening any of them.
 */
import { describe, expect, it } from 'vitest';
import {
  checkUrl,
  hostMatchesAllowlist,
  isAuthPathBlocked,
  isProtectedEndpoint,
  mergeSiteProfiles,
} from '@browser-bridge/policy';
import { ebaySiteProfile } from '@browser-bridge/site-ebay';
import { kijijiSiteProfile } from '@browser-bridge/site-kijiji';
import {
  isOfficeSourceHost,
  OFFICE_SOURCES,
  OFFICE_SOURCES_SITE_PROFILE_ID,
  officeSourcesSiteProfile,
} from '@browser-bridge/site-office';
import { wardrobeVendorsSiteProfile } from '@browser-bridge/site-vendors';
import { zazzleSiteProfile } from '@browser-bridge/site-zazzle';

const publicResolve = async () => ['23.55.0.10'];

describe('office-sources.v1 roster', () => {
  it('is a production profile with a versioned id and no test escapes', () => {
    expect(officeSourcesSiteProfile.id).toBe('office-sources.v1');
    expect(OFFICE_SOURCES_SITE_PROFILE_ID).toBe(officeSourcesSiteProfile.id);
    expect(officeSourcesSiteProfile.testOnly).toBeUndefined();
  });

  it('covers every host the 2026-09-05 ratification named, apex and subdomains', () => {
    const hosts = officeSourcesSiteProfile.allowedHosts;
    for (const host of [
      // providers
      'www.regus.com', 'regus.com', 'www.spacesworks.com', 'www.hq.com', 'www.industriousoffice.com',
      'www.wework.com', 'iqoffices.com', 'www.venturex.com', 'www.intelligentoffice.com', 'www.telsec.net',
      'workhaus.ca', 'www.workplaceone.com', 'zemlar.com', 'zemlar.ca', 'oneplan.ca', 'collabhive.ca',
      'www.gtexecutivecentre.com', 'studio.staples.ca', 'www.workplacek.com', 'office146.com',
      'www.thefuelingstation.com',
      // listing surfaces
      'www.realtor.ca', 'liquidspace.com', 'www.office-hub.com', 'www.spacelist.ca',
      'www.coworkingcafe.com', 'www.commercialcafe.com', 'www.loopnet.ca',
    ]) {
      expect(hostMatchesAllowlist(host, hosts), host).toBe(true);
      expect(isOfficeSourceHost(host), host).toBe(true);
    }
  });

  it('every roster entry names a public registrable domain (or a narrower host), a group and a source', () => {
    expect(OFFICE_SOURCES.length).toBeGreaterThanOrEqual(26);
    for (const source of OFFICE_SOURCES) {
      expect(['provider', 'listing']).toContain(source.group);
      expect(source.hosts.length).toBeGreaterThan(0);
      for (const host of source.hosts) {
        expect(host, host).toMatch(/^[a-z0-9-]+(?:\.[a-z0-9-]+)+$/);
        expect(host, host).not.toMatch(/^\d+\.\d+\.\d+\.\d+$/);
        expect(host, host).not.toMatch(/^\*/);
      }
      expect(source.addedOn).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(source.source.length).toBeGreaterThan(20);
    }
  });

  it('the Staples entry is the studio subdomain only: the retailer apex stays out', () => {
    const hosts = officeSourcesSiteProfile.allowedHosts;
    expect(hostMatchesAllowlist('studio.staples.ca', hosts)).toBe(true);
    expect(hostMatchesAllowlist('www.staples.ca', hosts)).toBe(false);
    expect(hostMatchesAllowlist('staples.ca', hosts)).toBe(false);
    expect(isOfficeSourceHost('https://www.staples.ca/cart')).toBe(false);
  });

  it('never matches lookalikes, marketplaces or the hosts other profiles own', () => {
    const hosts = officeSourcesSiteProfile.allowedHosts;
    for (const host of ['notregus.com', 'regus.com.attacker.io', 'realtor.ca.evil.example', 'loopnet.com', 'www.kijiji.ca', 'www.ebay.ca', 'www.zazzle.ca', 'www.vistaprint.ca']) {
      expect(hostMatchesAllowlist(host, hosts), host).toBe(false);
      expect(isOfficeSourceHost(host), host).toBe(false);
    }
    expect(isOfficeSourceHost('not a host')).toBe(false);
  });

  it('allows provider location pages and listing detail pages, and blocks their booking, quote, enquiry and sign-in paths', async () => {
    for (const url of [
      'https://www.regus.com/en/ca/ontario/toronto/office-space',
      'https://www.spacesworks.com/toronto/gladstone',
      'https://www.realtor.ca/real-estate/29488850/302-08-3390-south-service-road-burlington-industrial-burlington',
      'https://www.spacelist.ca/listings/toronto/280814',
      'https://www.loopnet.ca/for-lease/office/toronto-on/',
    ]) {
      const decision = await checkUrl(url, officeSourcesSiteProfile, 'navigation', { resolve: publicResolve });
      expect(decision.allowed, url).toBe(true);
      expect(isProtectedEndpoint(url, officeSourcesSiteProfile), url).toBe(false);
    }
    for (const url of [
      'https://www.regus.com/en-ca/booking/confirm',
      'https://liquidspace.com/reserve/12345',
      'https://www.realtor.ca/real-estate/29488850/contact-agent',
      'https://www.loopnet.ca/listing/123/inquiry',
      'https://www.spacelist.ca/checkout',
      'https://www.workhaus.ca/account/billing',
    ]) {
      expect(isProtectedEndpoint(url, officeSourcesSiteProfile), url).toBe(true);
    }
    for (const url of ['https://www.regus.com/en-ca/login', 'https://liquidspace.com/users/sign-in', 'https://www.realtor.ca/auth']) {
      expect(isAuthPathBlocked(url, officeSourcesSiteProfile), url).toBe(true);
      const decision = await checkUrl(url, officeSourcesSiteProfile, 'navigation', { resolve: publicResolve });
      expect(decision.allowed, url).toBe(false);
    }
  });

  // A listing slug is broker-written text: an endpoint word inside it is not an endpoint.
  it('does not treat an endpoint word inside a listing slug as an endpoint', () => {
    for (const url of [
      'https://www.spacelist.ca/listings/toronto/order-desk-building-suite-200',
      'https://www.realtor.ca/real-estate/1/1200-bay-st-cart-alley-unit-4',
      'https://www.regus.com/en-ca/canada/toronto/first-canadian-place-buying-guide',
    ]) {
      expect(isProtectedEndpoint(url, officeSourcesSiteProfile), url).toBe(false);
      expect(isAuthPathBlocked(url, officeSourcesSiteProfile), url).toBe(false);
    }
  });

  it('refuses the quote, tour, viewing and contact controls by accessible name, on top of the generic set', () => {
    for (const name of ['get a quote', 'request a quote', 'schedule a tour', 'book a viewing', 'enquire now', 'contact us', 'contact agent', 'book now', 'apply now', 'sign in', 'add to cart']) {
      expect(officeSourcesSiteProfile.blockedActionPatterns, name).toContain(name);
    }
    expect(officeSourcesSiteProfile.blockedFieldAutocomplete).toEqual(
      expect.arrayContaining(['current-password', 'new-password', 'one-time-code', 'cc-number', 'cc-exp', 'cc-csc']),
    );
  });

  it('is no weaker than the hand-written wardrobe lane', () => {
    expect(officeSourcesSiteProfile.blockedActionPatterns).toEqual(
      expect.arrayContaining([...wardrobeVendorsSiteProfile.blockedActionPatterns]),
    );
  });

  it('composes with the four existing profiles without loosening any of them', () => {
    const composite = mergeSiteProfiles([
      ebaySiteProfile,
      kijijiSiteProfile,
      zazzleSiteProfile,
      wardrobeVendorsSiteProfile,
      officeSourcesSiteProfile,
    ]);
    expect(composite.id).toBe('ebay.ca.v1+kijiji.ca.v1+zazzle.com.v1+wardrobe-vendors.v1+office-sources.v1');
    expect(hostMatchesAllowlist('www.regus.com', composite.allowedHosts)).toBe(true);
    expect(hostMatchesAllowlist('www.ebay.ca', composite.allowedHosts)).toBe(true);
    expect(isProtectedEndpoint('https://www.ebay.ca/placebid?item=1', composite)).toBe(true);
    expect(isProtectedEndpoint('https://www.zazzle.ca/co/cart', composite)).toBe(true);
    expect(isProtectedEndpoint('https://www.regus.com/en-ca/booking/confirm', composite)).toBe(true);
    expect(composite.deniedHosts).toEqual(expect.arrayContaining(['entripy.com']));
  });
});
